sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKP1VvVKxLA6MxS4XRy
    access-key-secret: 31dEPCfA5ibhV8lEktExQI2HEjbmrq
    bucket-name: sky-ff


